CREATE TABLE STUDENTS (
STUDENT_ID INT IDENTITY(1,1) PRIMARY KEY,
FIRST_NAME NVARCHAR (50) NOT NULL,
LAST_NAME NVARCHAR (50) NOT NULL,
GROUP_ID INT)
GO

ALTER TABLE STUDENTS
WITH CHECK ADD CONSTRAINT FK_GROUPS_GROUP_ID FOREIGN KEY (GROUP_ID)
REFERENCES GROUPS (GROUP_ID)
GO 
