SELECT COURSES.NAME AS COURSE_NAME, STUDENTS.FIRST_NAME, STUDENTS.LAST_NAME

FROM STUDENTS

INNER JOIN GROUPS
ON STUDENTS.GROUP_ID = GROUPS.GROUP_ID

INNER JOIN COURSES
ON GROUPS.COURSE_ID = COURSES.COURSE_ID

